- name: Install Apache (httpd)
  become: true
  ansible.builtin.dnf:
    name: httpd
    state: present

- name: Deploy index.html
  become: true
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: "0644"

- name: Enable and start Apache
  become: true
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true