- name: Configure web servers via SSM (No SSH / No Keys)
  hosts: role_web
  gather_facts: true

  vars:
    ansible_connection: amazon.aws.aws_ssm
    ansible_aws_ssm_region: ap-northeast-1
    ansible_aws_ssm_timeout: 120

  roles:
    - web